const timelineItems = [
  {
    id: "galatea",
    title: "Galatea",
    period: "années 1990",
    status: "à récupérer",
    actors: ["Louise Dabène", "Encarni Carrasco", "Jean-Pierre Chavagne"],
    description: "Série fondatrice de CD-ROM pour l'entraînement à la compréhension des langues romanes.",
  },
  {
    id: "galanet",
    title: "Galanet",
    period: "2001-2004 puis usages ultérieurs",
    status: "à récupérer",
    actors: ["Christian Degache", "Jean-Pierre Chavagne", "Encarni Carrasco"],
    description: "Plateforme de télécollaboration entre groupes, avec forums, chats, choix de thème et production collective.",
  },
  {
    id: "galapro",
    title: "Galapro",
    period: "années 2000",
    status: "fragile",
    actors: ["Encarni Carrasco", "Jean-Pierre Chavagne"],
    description: "Suite de Galanet orientée vers la formation de formateurs et la didactique de l'intercompréhension.",
  },
  {
    id: "redinter",
    title: "RedInter",
    period: "2008-2011 environ",
    status: "à vérifier",
    actors: ["réseau européen IC"],
    description: "Réseau européen structurant pour les acteurs, formations et échanges autour de l'intercompréhension.",
  },
  {
    id: "miriadi",
    title: "Miriadi",
    period: "2012-2015 puis usages ultérieurs",
    status: "fragile",
    actors: ["Christian Degache", "Jean-Pierre Chavagne", "Encarni Carrasco"],
    description: "Plateforme et réseau pour la mutualisation et l'innovation en intercompréhension à distance.",
  },
  {
    id: "lecturio",
    title: "Lecturio",
    period: "années 2010",
    status: "à vérifier",
    actors: ["APICAD", "Miriadi"],
    description: "Projet ou ressource lié à Miriadi, cité comme travail sur plurilinguisme et littératie.",
  },
  {
    id: "iplera",
    title: "IPLERA",
    period: "avant ALPAGA",
    status: "à vérifier",
    actors: ["Kátia", "Christian Degache"],
    description: "Projet Rhône-alpin lié aux politiques linguistiques universitaires et à leurs limites institutionnelles.",
  },
  {
    id: "alpaga",
    title: "ALPAGA",
    period: "années 2020",
    status: "vivant",
    actors: ["Kátia", "Christian Degache"],
    description: "Projet autour des pratiques plurilingues et de l'alternance, ayant commencé à constituer des corpus.",
  },
  {
    id: "repli4c",
    title: "REPLI4C",
    period: "projet actuel",
    status: "vivant",
    actors: ["Kátia", "Christian Degache", "équipe REPLI4C"],
    description: "Projet actuel centré sur les discours liés au changement climatique et cadre du stage-mémoire.",
  },
  {
    id: "prototypes-actuels",
    title: "Prototypes actuels",
    period: "2026",
    status: "vivant",
    actors: ["communauté IC"],
    description: "Série de prototypes expérimentaux visant à rendre visibles les besoins, outils et formes de l'intercompréhension.",
  },
];

const items = [
  {
    id: "galatea",
    title: "Galatea",
    type: "projet",
    status: "à récupérer",
    period: "années 1990",
    tags: ["CD-ROM", "compréhension écrite", "langues romanes", "historique"],
    actors: ["Louise Dabène", "Encarni Carrasco", "Jean-Pierre Chavagne"],
    interviews: ["Encarni", "Jean-Pierre", "Hugues", "Kátia"],
    description: "Ressource fondatrice de la saga Gala, souvent évoquée comme patrimoine ancien dont les supports et accès doivent être vérifiés.",
    risks: ["supports anciens", "accès incertain", "droits", "compatibilité"],
    recoverability: "partielle",
  },
  {
    id: "galanet",
    title: "Galanet",
    aliases: ["GalaNet", "Gala net", "Galanet plateforme", "Galanet project"],
    type: "projet",
    status: "à récupérer",
    period: "2001-2004 puis usages ultérieurs",
    tags: ["télécollaboration", "forum", "chat", "production collective", "historique"],
    actors: ["Christian Degache", "Jean-Pierre Chavagne", "Encarni Carrasco"],
    interviews: ["Encarni", "Jean-Pierre", "Christian", "Alice", "Hugues", "Sandrine"],
    description: "Plateforme historique d'intercompréhension en réseau de groupes, structurée en phases et productions communes.",
    risks: ["technologie ancienne", "données non récupérées", "maintenance", "droits"],
    recoverability: "partielle",
  },
  {
    id: "galapro",
    title: "Galapro",
    aliases: ["GalaPro", "Gala pro", "Galapro formation", "Galanet Galapro"],
    type: "projet",
    status: "fragile",
    period: "années 2000",
    tags: ["formation de formateurs", "didactique", "plateforme", "historique"],
    actors: ["Encarni Carrasco", "Jean-Pierre Chavagne"],
    interviews: ["Encarni", "Jean-Pierre", "Alice", "Hugues"],
    description: "Projet issu de Galanet, orienté vers la formation de futurs enseignants et formateurs en intercompréhension.",
    risks: ["plateforme ancienne", "traces dispersées", "contenus à inventorier"],
    recoverability: "incertaine",
  },
  {
    id: "miriadi",
    title: "Miriadi",
    aliases: ["Myriadi", "MIRIADI", "Miriadi réseau", "Miriadi plateforme"],
    type: "plateforme",
    status: "fragile",
    period: "2012-2015 puis usages ultérieurs",
    tags: ["mutualisation", "sessions", "réseau", "plateforme"],
    actors: ["Christian Degache", "Jean-Pierre Chavagne", "Encarni Carrasco", "APICAD"],
    interviews: ["Christian", "Encarni", "Jean-Pierre", "Sandrine", "Hugues"],
    description: "Plateforme et projet de mutualisation pour l'intercompréhension à distance, fréquemment cités comme réservoir de ressources.",
    risks: ["maintenance", "pérennisation", "migration", "dynamique de réseau"],
    recoverability: "bonne mais à vérifier",
  },
  {
    id: "redinter",
    title: "RedInter",
    type: "projet",
    status: "à vérifier",
    period: "2008-2011 environ",
    tags: ["réseau", "Europe", "formation", "historique"],
    actors: ["réseau européen IC"],
    interviews: ["à compléter"],
    description: "Réseau européen à replacer dans la généalogie des projets IC et dans les connexions entre institutions.",
    risks: ["références à vérifier", "chronologie à consolider"],
    recoverability: "inconnue",
    uncertain: true,
  },
  {
    id: "lecturio",
    title: "Lecturio",
    type: "ressource",
    status: "à vérifier",
    period: "années 2010",
    tags: ["Miriadi", "littératie", "enfants", "plurilinguisme"],
    actors: ["APICAD", "Encarni Carrasco", "Jean-Pierre Chavagne"],
    interviews: ["Encarni", "Jean-Pierre"],
    description: "Projet ou ressource mentionné dans l'environnement Miriadi, à documenter plus précisément.",
    risks: ["nom exact", "accès", "statut actuel"],
    recoverability: "à vérifier",
    uncertain: true,
  },
  {
    id: "iplera",
    title: "IPLERA",
    aliases: ["IPLER", "Iplera", "Iplera Rhône-Alpes", "IPLERA Rhône-Alpes"],
    type: "projet",
    status: "à vérifier",
    period: "avant ALPAGA",
    tags: ["politiques linguistiques", "université", "Rhône-Alpes", "Genève"],
    actors: ["Kátia", "Christian Degache"],
    interviews: ["Kátia", "Christian"],
    description: "Projet antérieur lié aux politiques linguistiques universitaires, cité comme étape vers ALPAGA.",
    risks: ["sigle à stabiliser", "documents à retrouver"],
    recoverability: "à vérifier",
  },
  {
    id: "alpaga",
    title: "ALPAGA",
    aliases: ["Alpaga", "ALPAGA corpus", "projet ALPAGA"],
    type: "projet",
    status: "vivant",
    period: "années 2020",
    tags: ["corpus", "alternance", "pratiques plurilingues", "consentement"],
    actors: ["Kátia", "Christian Degache"],
    interviews: ["Kátia", "Christian", "Alice", "Sandrine"],
    description: "Projet ayant commencé à constituer des corpus et à formaliser des questions de consentement et de ressources réutilisables.",
    risks: ["formats", "migrations futures", "documentation"],
    recoverability: "bonne",
  },
  {
    id: "repli4c",
    title: "REPLI4C",
    aliases: ["Repli4C", "REPLI 4C", "Repli 4C", "Reply for C", "Reply4C"],
    type: "projet",
    status: "vivant",
    period: "projet actuel",
    tags: ["climat", "discours", "corpus", "stage"],
    actors: ["Kátia", "Christian Degache", "équipe REPLI4C"],
    interviews: ["Kátia", "Christian"],
    description: "Projet dans lequel s'inscrit le stage, autour des récits et discours liés aux conséquences du changement climatique.",
    risks: ["outillage corpus", "transcription", "annotation", "formats durables"],
    recoverability: "bonne",
  },
  {
    id: "apicad",
    title: "APICAD",
    aliases: ["Apicad", "APICAD association", "Association APICAD"],
    type: "acteur collectif",
    status: "vivant",
    period: "après Miriadi",
    tags: ["association", "réseau", "maintenance", "promotion IC"],
    actors: ["Christian Degache", "Jean-Pierre Chavagne"],
    interviews: ["Christian", "Jean-Pierre", "Hugues"],
    description: "Association évoquée comme structure de prolongement de Miriadi et de maintien des ressources d'intercompréhension à distance.",
    risks: ["dynamique sans projet financé", "webmaster", "maintenance"],
    recoverability: "bonne",
  },
  {
    id: "eurom",
    title: "EuRom / EuRom Web",
    aliases: ["EuRom 4", "EuRom 5", "EuRom5", "Eurom 5", "Eurom5", "EuRom Web", "EuroComRom", "EuRomWeb"],
    type: "ressource",
    status: "vivant",
    period: "méthode historique et versions web",
    tags: ["manuel", "compréhension écrite", "audio", "langues romanes"],
    actors: ["Sandra", "Laura", "Hugues", "Richard"],
    interviews: ["Alice", "Giovanna", "Hugues", "Jean-Pierre", "Laura", "Richard", "Sandra"],
    description: "Méthode de référence très citée, avec versions papier et web ; sert de repère pour la compréhension écrite et certains besoins audio.",
    risks: ["noms transcrits variables", "versions à distinguer"],
    recoverability: "bonne",
  },
  {
    id: "romanofonia-cinema",
    title: "Romanofonía y Cinema",
    aliases: ["Romanofonia y Cinema", "Romanofonía", "Romanofonia", "Romanophonie", "Romanophonie et cinéma", "Romanofonia Cinema"],
    type: "ressource",
    status: "vivant",
    period: "sessions récentes",
    tags: ["Moodle", "télécollaboration", "interproduction", "corpus"],
    actors: ["Christian Degache", "Kátia", "Elena"],
    interviews: ["Christian", "Kátia", "Elena"],
    description: "Dispositif de télécollaboration héritier des modèles historiques, passé de Miriadi à Moodle.",
    risks: ["export/import Moodle", "pérennisation des sessions"],
    recoverability: "bonne",
  },
  {
    id: "elementi-unito",
    title: "Elementi di intercomprensione UniTO",
    aliases: ["Elementi", "Elementi UniTO", "Elementi di intercomprensione", "Elementi di intercomprensione Unito", "Università di Torino intercomprensione"],
    type: "ressource",
    status: "vivant",
    period: "cours actuel",
    tags: ["Moodle", "cours ouvert", "vidéos", "quiz"],
    actors: ["Sandra"],
    interviews: ["Sandra"],
    description: "Cours autonome ouvert d'intercompréhension avec textes, vidéos, quiz et supports pour étudiants.",
    risks: ["accès à documenter", "droits de reprise"],
    recoverability: "bonne",
  },
  {
    id: "speechmatics",
    title: "Speechmatics",
    aliases: ["Speechmatics transcription", "Speechmatics ASR", "Speechmatics oral"],
    type: "outil",
    status: "vivant",
    period: "usage actuel",
    tags: ["transcription", "oral", "IA", "corpus"],
    actors: ["Sandra"],
    interviews: ["Sandra"],
    description: "Outil de transcription automatique utilisé pour produire une première transcription avant reprise manuelle.",
    risks: ["qualité selon langue", "segmentation", "coût", "données"],
    recoverability: "bonne",
  },
  {
    id: "elan",
    title: "ELAN",
    aliases: ["Elan", "ELAN annotation", "ELAN corpus", "EUDICO Linguistic Annotator"],
    type: "outil",
    status: "vivant",
    period: "usage actuel",
    tags: ["annotation", "oral", "multimodal", "corpus"],
    actors: ["Sandra"],
    interviews: ["Sandra", "Sandrine"],
    description: "Logiciel central pour l'annotation fine des interactions, avec alignement, segmentation et transcription.",
    risks: ["courbe d'apprentissage", "formats", "temps d'annotation"],
    recoverability: "bonne",
  },
  {
    id: "nosketch-kiparla",
    title: "NoSketch Engine / KiParla",
    type: "corpus",
    status: "à vérifier",
    period: "référence actuelle",
    tags: ["corpus", "consultation", "oral", "métadonnées"],
    actors: ["Sandra", "collègues turinois"],
    interviews: ["Sandra"],
    description: "Référence de corpus et d'outil de consultation citée via Sandra ; le nom et les modalités exactes doivent être stabilisés.",
    risks: ["nom transcrit", "accès", "modèle de métadonnées"],
    recoverability: "à vérifier",
    uncertain: true,
  },
  {
    id: "phip",
    title: "PHIP - Historias Infantiles Plurilingües",
    aliases: ["PHIP", "Historias Infantiles Plurilingues", "Historias Infantiles Plurilingües", "Histoires infantiles plurilingues"],
    type: "ressource",
    status: "vivant",
    period: "projet actuel",
    tags: ["contes", "plurilinguisme", "portail", "HTML"],
    actors: ["Richard"],
    interviews: ["Richard"],
    description: "Portail de contes plurilingues porté par Richard, avec une dimension de production et de mise à disposition.",
    risks: ["maintenance personnelle", "documentation technique"],
    recoverability: "bonne",
  },
  {
    id: "itineraires-romans",
    title: "Itinéraires romans",
    aliases: ["Itineraires romans", "Itinéraires Roman", "Itinerarios románicos", "Itineraires romans Union Latine"],
    type: "ressource",
    status: "disparu",
    period: "Union Latine",
    tags: ["enfants", "Union Latine", "historique", "ressource web"],
    actors: ["Union Latine", "Encarni Carrasco"],
    interviews: ["Encarni", "Hugues"],
    description: "Ressource historique pour enfants, souvent associée aux enjeux de ressources perdues ou difficiles à réactiver.",
    risks: ["Flash", "site disparu", "archives partielles", "droits"],
    recoverability: "incertaine",
  },
  {
    id: "portail-ple-katia",
    title: "Portail PLE cité par Kátia",
    type: "ressource",
    status: "à vérifier",
    period: "à documenter",
    tags: ["portail", "ressources", "PLE", "référence incertaine"],
    actors: ["Kátia"],
    interviews: ["Kátia"],
    description: "Portail mentionné comme référence utile ; la source, le périmètre et l'accès restent à préciser.",
    risks: ["nom exact", "URL", "statut actuel"],
    recoverability: "à vérifier",
    uncertain: true,
  },
  {
    id: "aides-comprehension-orale",
    title: "Aides à la compréhension orale",
    type: "concept",
    status: "fragile",
    period: "besoin récurrent",
    tags: ["oral", "didactisation", "guidage", "niveau 2"],
    actors: ["Laura", "Alice", "Sandra", "Jean-Pierre Chavagne"],
    interviews: ["Laura", "Alice", "Sandra", "Jean-Pierre"],
    description: "Besoin d'outils et de ressources pour accompagner l'oral, souvent moins couvert que la compréhension écrite.",
    risks: ["ressources rares", "transcription", "annotation", "scénarisation"],
    recoverability: "à construire",
  },
  {
    id: "corpus-videos",
    title: "Corpus et vidéos non encore exploitables",
    type: "corpus",
    status: "fragile",
    period: "chantier actuel",
    tags: ["vidéo", "oral", "consentement", "transcription"],
    actors: ["Alice", "Kátia", "Christian Degache", "Sandra"],
    interviews: ["Alice", "Kátia", "Christian", "Sandra"],
    description: "Réunions, sessions et traces audiovisuelles potentiellement riches, mais dépendantes de la qualité, du consentement et des formats.",
    risks: ["consentement", "qualité audio", "formats", "annotation"],
    recoverability: "partielle",
  },
  {
    id: "christian",
    title: "Christian Degache",
    type: "acteur",
    status: "vivant",
    period: "acteur historique et actuel",
    tags: ["Galanet", "Miriadi", "ALPAGA", "REPLI4C", "Romanofonía"],
    actors: ["Christian Degache"],
    interviews: ["Christian", "Encarni", "Jean-Pierre", "Kátia", "Laura", "Roxana", "Thomas"],
    description: "Acteur central des dispositifs historiques et actuels, associé à la télécollaboration, aux corpus et à REPLI4C.",
    risks: ["capitalisation des traces", "dispersion des projets"],
    recoverability: "bonne",
  },
  {
    id: "encarni",
    title: "Encarni Carrasco",
    type: "acteur",
    status: "vivant",
    period: "actrice historique",
    tags: ["Galatea", "Galanet", "Galapro", "Miriadi", "Lecturio"],
    actors: ["Encarni Carrasco"],
    interviews: ["Encarni", "Christian", "Jean-Pierre"],
    description: "Personne ressource pour la généalogie Gala et les plateformes historiques, avec des repères précis sur les étapes successives.",
    risks: ["traces à collecter", "chronologie fine"],
    recoverability: "bonne",
  },
  {
    id: "jean-pierre",
    title: "Jean-Pierre Chavagne",
    type: "acteur",
    status: "vivant",
    period: "acteur historique",
    tags: ["Galanet", "Galapro", "Miriadi", "APICAD", "EuRom"],
    actors: ["Jean-Pierre Chavagne"],
    interviews: ["Jean-Pierre", "Encarni", "Christian", "Hugues"],
    description: "Acteur clé pour les plateformes historiques, les enjeux de récupération et la mémoire technique des projets.",
    risks: ["archives à localiser", "captures et traces"],
    recoverability: "bonne",
  },
  {
    id: "katia",
    title: "Kátia",
    type: "acteur",
    status: "vivant",
    period: "actrice actuelle",
    tags: ["IPLERA", "ALPAGA", "REPLI4C", "bibliothèque", "corpus"],
    actors: ["Kátia"],
    interviews: ["Kátia", "Teurra"],
    description: "Actrice centrale pour IPLERA, ALPAGA et REPLI4C, avec un accent fort sur la pérennisation et la bibliothèque de ressources.",
    risks: ["formats durables", "centralisation"],
    recoverability: "bonne",
  },
  {
    id: "sandra",
    title: "Sandra Garbarino",
    type: "acteur",
    status: "vivant",
    period: "actrice corpus/oral",
    tags: ["EuRom Web", "Speechmatics", "ELAN", "NoSketch", "KiParla", "intercompréhension", "recherche", "enseignement"],
    actors: ["Sandra Garbarino"],
    interviews: ["Sandra", "Alice", "Encarni", "Jean-Pierre"],
    description: "Personne interviewée et citée, ressource sur la transcription, l'annotation, les corpus oraux, l'outillage de recherche et les usages d'EuRom Web.",
    risks: ["charge d'annotation", "interopérabilité", "contexte des citations à préciser"],
    recoverability: "bonne",
  },
  {
    id: "alice",
    title: "Alice",
    type: "acteur",
    status: "vivant",
    period: "actrice pédagogique",
    tags: ["COIL", "oral", "Galanet", "ALPAGA", "EuRom"],
    actors: ["Alice"],
    interviews: ["Alice", "Sandra", "Thomas"],
    description: "Entretien centré sur les dispositifs pédagogiques, les reprises du modèle Galanet et les matériaux oraux potentiels.",
    risks: ["vidéos à exploiter", "scénarios à formaliser"],
    recoverability: "bonne",
  },
  {
    id: "hugues",
    title: "Hugues Sheeren",
    type: "acteur",
    status: "vivant",
    period: "acteur ressource",
    tags: ["EuRom", "Miriadi", "APICAD", "maintenance"],
    actors: ["Hugues Sheeren"],
    interviews: ["Hugues", "Jean-Pierre"],
    description: "Acteur important pour les ressources, leur modernisation et la question concrète de la maintenance web.",
    risks: ["ressources à documenter", "maintenance"],
    recoverability: "bonne",
  },
  {
    id: "richard",
    title: "Richard",
    type: "acteur",
    status: "vivant",
    period: "acteur ressource",
    tags: ["PHIP", "EuRom", "dictionnaire", "transcription"],
    actors: ["Richard"],
    interviews: ["Richard", "Hugues", "Jean-Pierre"],
    description: "Porteur du portail PHIP et témoin de l'entrée dans l'intercompréhension par EuRom.",
    risks: ["documentation du portail", "maintenance"],
    recoverability: "bonne",
  },
  {
    id: "thomas",
    title: "Thomas",
    type: "acteur",
    status: "vivant",
    period: "acteur pédagogique",
    tags: ["oral", "interproduction", "dictionnaire", "enseignement"],
    actors: ["Thomas"],
    interviews: ["Thomas"],
    description: "Entretien utile pour les besoins pédagogiques, l'oral et les outils d'accompagnement.",
    risks: ["liens à compléter"],
    recoverability: "bonne",
  },
  {
    id: "centralisation",
    title: "Centraliser sans figer",
    type: "besoin",
    status: "vivant",
    period: "besoin transversal",
    tags: ["bibliothèque", "moteur de recherche", "mutualisation", "pérennisation"],
    actors: ["Kátia", "Christian Degache", "Sandrine", "Hugues"],
    interviews: ["Kátia", "Christian", "Sandrine", "Hugues"],
    description: "Besoin de retrouver les ressources sans les enfermer : un point d'entrée commun, documenté et maintenable.",
    risks: ["données incomplètes", "gouvernance", "maintenance"],
    recoverability: "à construire",
  },
  {
    id: "dictionnaire-strategique",
    title: "Dictionnaire stratégique",
    type: "besoin",
    status: "vivant",
    period: "besoin transversal",
    tags: ["lexique", "stratégies", "didactique", "enseignants"],
    actors: ["Christian Degache", "Laura", "Richard", "Roxana"],
    interviews: ["Christian", "Laura", "Richard", "Roxana", "Alice"],
    description: "Idée récurrente d'un dictionnaire ou répertoire de stratégies pour aider à comprendre, enseigner et remixer.",
    risks: ["modèle de données", "granularité", "validation scientifique"],
    recoverability: "à construire",
  },
  {
    id: "annotation-transcription",
    title: "Transcrire et annoter",
    type: "besoin",
    status: "vivant",
    period: "besoin transversal",
    tags: ["transcription", "annotation", "oral", "IA", "ELAN"],
    actors: ["Sandra", "Alice", "Laura", "Richard"],
    interviews: ["Sandra", "Alice", "Laura", "Richard", "Sandrine"],
    description: "Besoin transversal pour transformer les traces orales et vidéos en ressources analysables, didactisables et réutilisables.",
    risks: ["temps humain", "qualité automatique", "standards", "consentement"],
    recoverability: "à construire",
  },
];

items.push(
  {
    id: "archives-miriadi-anciennes",
    title: "Archives Miriadi anciennes",
    type: "ressource",
    status: "à récupérer",
    period: "après 2012",
    tags: ["Miriadi", "archives", "sessions", "plateforme"],
    actors: ["APICAD", "Jean-Pierre Chavagne", "Christian Degache"],
    interviews: ["Christian", "Jean-Pierre", "Encarni", "Sandrine"],
    description: "Ensemble de traces, sessions et ressources anciennes liées à Miriadi, à inventorier avant toute récupération technique.",
    risks: ["accès", "droits", "migration", "maintenance"],
    recoverability: "partielle",
    uncertain: true,
  },
  {
    id: "ressources-unita",
    title: "Ressources UNITA",
    type: "ressource",
    status: "à vérifier",
    period: "usages actuels",
    tags: ["UNITA", "réunions", "oral", "vidéo", "intercompréhension"],
    actors: ["Alice", "Kátia"],
    interviews: ["Alice"],
    description: "Réunions et ressources potentielles évoquées comme matériau oral ou vidéo exploitable pour l'intercompréhension.",
    risks: ["qualité audio", "consentement", "formats", "accès"],
    recoverability: "à vérifier",
    uncertain: true,
  },
  {
    id: "corpus-multimodal",
    title: "Corpus multimodal",
    type: "corpus",
    status: "fragile",
    period: "chantier transversal",
    tags: ["oral", "vidéo", "annotation", "transcription", "métadonnées"],
    actors: ["Sandra", "Alice", "Kátia", "Christian Degache"],
    interviews: ["Sandra", "Alice", "Kátia", "Christian"],
    description: "Concept de corpus reliant traces orales, vidéo, transcriptions, annotations et métadonnées pour rendre les interactions exploitables.",
    risks: ["interopérabilité", "temps d'annotation", "formats", "consentement"],
    recoverability: "à construire",
  },
  {
    id: "moodle",
    title: "Moodle",
    type: "outil",
    status: "vivant",
    period: "usage actuel",
    tags: ["LMS", "cours", "Romanofonía", "export", "import"],
    actors: ["Christian Degache", "Sandra"],
    interviews: ["Christian", "Sandra"],
    description: "Infrastructure d'hébergement de cours et sessions, notamment pour Romanofonía y Cinema et certains cours ouverts.",
    risks: ["export/import", "pérennisation", "dépendance institutionnelle"],
    recoverability: "bonne",
  },
  {
    id: "evaluation",
    title: "Évaluation",
    type: "concept",
    status: "à vérifier",
    period: "besoin transversal",
    tags: ["formation", "didactique", "sessions", "formateurs"],
    actors: ["Encarni Carrasco", "Jean-Pierre Chavagne"],
    interviews: ["Encarni", "Jean-Pierre"],
    description: "Dimension à documenter dans les dispositifs de formation et les plateformes historiques, notamment Galapro et Miriadi.",
    risks: ["critères dispersés", "traces pédagogiques à retrouver"],
    recoverability: "à documenter",
  },
  {
    id: "sdl",
    title: "Sciences du langage",
    type: "concept",
    status: "vivant",
    period: "cadre disciplinaire",
    tags: ["SDL", "université", "politique linguistique", "formation"],
    actors: ["Kátia"],
    interviews: ["Kátia"],
    description: "Cadre disciplinaire lié aux politiques linguistiques, aux formations universitaires et à la pérennisation des ressources.",
    risks: ["liens institutionnels à préciser"],
    recoverability: "bonne",
  },
  {
    id: "politique-linguistique",
    title: "Politique linguistique",
    type: "concept",
    status: "vivant",
    period: "besoin institutionnel",
    tags: ["université", "IPLERA", "ALPAGA", "formation"],
    actors: ["Kátia", "Christian Degache"],
    interviews: ["Kátia", "Christian"],
    description: "Question transversale reliant IPLERA, ALPAGA et les limites des politiques linguistiques universitaires.",
    risks: ["documentation institutionnelle", "continuité entre projets"],
    recoverability: "bonne",
  },
  {
    id: "perennisation",
    title: "Pérennisation",
    type: "besoin",
    status: "vivant",
    period: "besoin transversal",
    tags: ["maintenance", "formats", "archives", "transmission"],
    actors: ["Kátia", "Christian Degache", "Hugues Sheeren", "Jean-Pierre Chavagne"],
    interviews: ["Kátia", "Christian", "Hugues", "Jean-Pierre"],
    description: "Besoin de maintenir les ressources dans le temps par des formats durables, des responsables identifiés et une documentation transmissible.",
    risks: ["dépendance individuelle", "outils obsolètes", "financement"],
    recoverability: "à construire",
  },
  {
    id: "laura",
    title: "Laura",
    type: "acteur",
    status: "vivant",
    period: "actrice pédagogique",
    tags: ["EuRom", "oral", "dictionnaire", "compréhension"],
    actors: ["Laura"],
    interviews: ["Laura"],
    description: "Entretien important pour les besoins liés à l'oral, au niveau 2 et aux outils d'accompagnement des apprenants.",
    risks: ["besoins à formaliser", "ressources orales à inventorier"],
    recoverability: "bonne",
  }
);

items.push(
  {
    id: "teurra",
    title: "Teurra",
    type: "acteur",
    status: "à vérifier",
    period: "personne interviewée",
    tags: ["entretien", "acteur", "à vérifier"],
    actors: ["Teurra"],
    interviews: ["Teurra"],
    description: "Personne interviewée du corpus, à documenter plus finement dans le registre d'acteurs.",
    risks: ["nom complet à vérifier", "domaines à préciser"],
    recoverability: "à documenter",
    confidence: "à vérifier",
    sourceStatus: "nom complet à vérifier",
    todo: ["Vérifier le nom complet"],
  },
  {
    id: "giovanna",
    title: "Giovanna",
    type: "acteur",
    status: "à vérifier",
    period: "personne interviewée",
    tags: ["entretien", "acteur", "EuRom"],
    actors: ["Giovanna"],
    interviews: ["Giovanna"],
    description: "Personne interviewée du corpus, associée aux ressources et usages à préciser.",
    risks: ["nom complet à vérifier", "domaines à préciser"],
    recoverability: "à documenter",
    confidence: "à vérifier",
    sourceStatus: "nom complet à vérifier",
    todo: ["Vérifier le nom complet"],
  },
  {
    id: "elena",
    title: "Elena",
    type: "acteur",
    status: "à vérifier",
    period: "personne interviewée",
    tags: ["entretien", "acteur", "Romanofonía"],
    actors: ["Elena"],
    interviews: ["Elena"],
    description: "Personne interviewée du corpus, liée aux dispositifs actuels à documenter.",
    risks: ["nom complet à vérifier", "domaines à préciser"],
    recoverability: "à documenter",
    confidence: "à vérifier",
    sourceStatus: "nom complet à vérifier",
    todo: ["Vérifier le nom complet"],
  },
  {
    id: "roxana",
    title: "Roxana",
    type: "acteur",
    status: "à vérifier",
    period: "personne interviewée",
    tags: ["entretien", "acteur", "dictionnaire stratégique"],
    actors: ["Roxana"],
    interviews: ["Roxana"],
    description: "Personne interviewée du corpus, utile pour compléter les besoins et ressources cités.",
    risks: ["nom complet à vérifier", "domaines à préciser"],
    recoverability: "à documenter",
    confidence: "à vérifier",
    sourceStatus: "nom complet à vérifier",
    todo: ["Vérifier le nom complet"],
  },
  {
    id: "sandrine",
    title: "Sandrine",
    type: "acteur",
    status: "à vérifier",
    period: "personne interviewée",
    tags: ["entretien", "acteur", "centralisation", "annotation"],
    actors: ["Sandrine"],
    interviews: ["Sandrine"],
    description: "Personne interviewée du corpus, associée aux besoins de centralisation, annotation et ressources.",
    risks: ["nom complet à vérifier", "domaines à préciser"],
    recoverability: "à documenter",
    confidence: "à vérifier",
    sourceStatus: "nom complet à vérifier",
    todo: ["Vérifier le nom complet"],
  },
  {
    id: "louise-dabene",
    title: "Louise Dabène",
    type: "acteur",
    status: "historique",
    period: "personne citée",
    tags: ["didactique", "intercompréhension", "histoire"],
    actors: ["Louise Dabène"],
    interviews: ["à compléter"],
    description: "Personne citée comme repère historique majeur de l'intercompréhension et de sa didactique.",
    risks: ["rôle exact à préciser dans les entretiens"],
    recoverability: "à documenter",
  },
  {
    id: "claire-blanche-benveniste",
    title: "Claire Blanche-Benveniste",
    type: "acteur",
    status: "historique",
    period: "personne citée",
    tags: ["EuRom", "linguistique", "langues romanes"],
    actors: ["Claire Blanche-Benveniste"],
    interviews: ["à compléter"],
    description: "Personne citée comme figure importante pour EuRom et les approches romanes de l'intercompréhension.",
    risks: ["rôle exact à préciser dans les entretiens"],
    recoverability: "à documenter",
  },
  {
    id: "paula-leone",
    title: "Paula Leone",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["intercompréhension", "recherche", "enseignement"],
    actors: ["Paula Leone"],
    interviews: ["à compléter"],
    description: "Personne citée de façon significative dans les entretiens, à documenter dans le registre.",
    risks: ["contexte de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "mariana-frontini",
    title: "Mariana Frontini",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["corpus", "ressources", "intercompréhension"],
    actors: ["Mariana Frontini"],
    interviews: ["à compléter"],
    description: "Personne citée dans le corpus, à relier aux projets et ressources concernés.",
    risks: ["contexte de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "laurent-baque",
    title: "Laurent Baqué",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["oral", "phonétique", "intercompréhension"],
    actors: ["Laurent Baqué"],
    interviews: ["à compléter"],
    description: "Personne citée dans les entretiens, probablement liée aux questions d'oral ou de phonétique à vérifier.",
    risks: ["domaine exact à vérifier"],
    recoverability: "à documenter",
  },
  {
    id: "eric-martin-marteau",
    title: "Eric Martin / Éric Marteau",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["nom incertain", "intercompréhension"],
    actors: ["Eric Martin / Éric Marteau"],
    interviews: ["à compléter"],
    description: "Personne citée avec un nom incertain ; la graphie et l'identité doivent être vérifiées.",
    risks: ["nom exact à vérifier", "doublon possible"],
    recoverability: "à documenter",
    uncertain: true,
    confidence: "à vérifier",
    sourceStatus: "nom exact à vérifier",
    todo: ["Vérifier s'il s'agit d'Eric Martin, Éric Marteau ou d'une autre personne."],
  },
  {
    id: "raquel-serrano-lopez",
    title: "Raquel Serrano López",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["intercompréhension", "enseignement", "recherche"],
    actors: ["Raquel Serrano López"],
    interviews: ["à compléter"],
    description: "Personne citée dans les entretiens, à relier aux ressources ou projets concernés.",
    risks: ["contexte de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "magdalena-de-carlo",
    title: "Magdalena de Carlo",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["intercompréhension", "didactique", "formation"],
    actors: ["Magdalena de Carlo"],
    interviews: ["à compléter"],
    description: "Personne citée de façon significative dans les entretiens, à documenter.",
    risks: ["contexte de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "lia-escarpe",
    title: "Lia Escarpe",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["intercompréhension", "ressources"],
    actors: ["Lia Escarpe"],
    interviews: ["à compléter"],
    description: "Personne citée dans les entretiens, à relier aux ressources et domaines exacts.",
    risks: ["contexte de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "robin-bright",
    title: "Robin Bright",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["intercompréhension", "outillage", "ressources"],
    actors: ["Robin Bright"],
    interviews: ["à compléter"],
    description: "Personne citée dans les entretiens, à documenter dans le registre d'acteurs.",
    risks: ["contexte de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "timothee-liotard",
    title: "Timothée Liotard",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["intercompréhension", "outillage", "ressources"],
    actors: ["Timothée Liotard"],
    interviews: ["à compléter"],
    description: "Personne citée dans les entretiens, à relier aux projets ou ressources concernés.",
    risks: ["contexte de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "philippe-blanchet",
    title: "Philippe Blanchet",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["sociolinguistique", "didactique", "politique linguistique"],
    actors: ["Philippe Blanchet"],
    interviews: ["à compléter"],
    description: "Personne citée comme repère à documenter pour les enjeux de langue, didactique ou politique linguistique.",
    risks: ["contexte de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "pierre-escude",
    title: "Pierre Escudé",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["intercompréhension", "didactique", "langues romanes"],
    actors: ["Pierre Escudé"],
    interviews: ["à compléter"],
    description: "Personne citée comme acteur ou repère du domaine, à documenter.",
    risks: ["contexte de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "francisco-calvo-del-olmo",
    title: "Francisco Calvo del Olmo / Paco",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["intercompréhension", "langues romanes", "Paco"],
    actors: ["Francisco Calvo del Olmo / Paco"],
    interviews: ["à compléter"],
    description: "Personne citée aussi sous le prénom Paco, à relier aux projets ou ressources concernés.",
    risks: ["périmètre de citation à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "salman-khan",
    title: "Salman Khan",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["référence externe", "pédagogie", "ressources"],
    actors: ["Salman Khan"],
    interviews: ["à compléter"],
    description: "Personne citée comme référence externe possible, probablement liée aux formats pédagogiques ou ressources en ligne.",
    risks: ["pertinence exacte à préciser"],
    recoverability: "à documenter",
  },
  {
    id: "hugo-professor-hugo",
    title: "Hugo / Professor Hugo",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["nom incertain", "ressource", "pédagogie"],
    actors: ["Hugo / Professor Hugo"],
    interviews: ["à compléter"],
    description: "Personne ou référence citée avec une identité à vérifier.",
    risks: ["nom exact à vérifier", "statut personne ou ressource à clarifier"],
    recoverability: "à documenter",
    uncertain: true,
    confidence: "à vérifier",
    sourceStatus: "nom exact à vérifier",
    todo: ["Vérifier l'identité et le statut de Hugo / Professor Hugo."],
  },
  {
    id: "chassagne-castagne-reims",
    title: "Chassagne / Castagne à Reims",
    type: "acteur",
    status: "à vérifier",
    period: "personne citée",
    tags: ["nom incertain", "Reims", "intercompréhension"],
    actors: ["Chassagne / Castagne à Reims"],
    interviews: ["à compléter"],
    description: "Personne citée avec graphie incertaine, à vérifier avant toute consolidation.",
    risks: ["nom exact à vérifier", "contexte de citation à préciser"],
    recoverability: "à documenter",
    uncertain: true,
    confidence: "à vérifier",
    sourceStatus: "nom exact à vérifier",
    todo: ["Vérifier la graphie Chassagne ou Castagne et le rattachement à Reims."],
  }
);

const itemAugmentations = {
  galatea: {
    relatedItems: ["galanet", "itineraires-romans", "encarni", "jean-pierre"],
    evidence: [
      { interview: "Encarni", note: "Situe Galatea comme première étape de la saga Gala avant Galanet et Galapro." },
      { interview: "Jean-Pierre Chavagne", note: "Rattache Galatea aux premiers dispositifs de compréhension des langues romanes." },
      { interview: "Hugues", note: "L'évoque comme patrimoine numérique ancien difficilement accessible." },
    ],
    recovery: {
      priority: "haute",
      status: "à contacter",
      nextAction: "Identifier les exemplaires, captures ou fichiers de CD-ROM encore disponibles et vérifier les droits.",
      responsible: "à définir",
      contacts: ["encarni", "jean-pierre", "hugues"],
    },
  },
  galanet: {
    relatedItems: ["galatea", "galapro", "miriadi", "encarni", "jean-pierre", "christian"],
    evidence: [
      { interview: "Jean-Pierre Chavagne", note: "Décrit Galanet comme plateforme centrale avec forum, chat, dépôt de documents et production collective." },
      { interview: "Encarni", note: "Situe Galanet dans la saga Galatea -> Galanet -> Galapro -> Miriadi." },
      { interview: "Alice", note: "Rapproche certains dispositifs COIL du modèle Galanet en phases." },
    ],
    recovery: {
      priority: "haute",
      status: "à contacter",
      nextAction: "Demander à Christian, Jean-Pierre et Encarni s'ils disposent de captures, exports ou archives.",
      responsible: "à définir",
      contacts: ["christian", "jean-pierre", "encarni"],
    },
  },
  galapro: {
    relatedItems: ["galanet", "miriadi", "evaluation", "encarni", "jean-pierre"],
    evidence: [
      { interview: "Encarni", note: "Présente Galapro comme suite de Galanet orientée vers la didactique et les formateurs." },
      { interview: "Jean-Pierre Chavagne", note: "Le relie aux formations de formateurs et aux plateformes historiques." },
      { interview: "Alice", note: "Cite Galapro avec Galanet comme modèle de projet IC structuré." },
    ],
    recovery: {
      priority: "haute",
      status: "à inventorier",
      nextAction: "Lister les modules, traces pédagogiques et critères d'évaluation récupérables.",
      responsible: "à définir",
      contacts: ["encarni", "jean-pierre"],
    },
  },
  miriadi: {
    relatedItems: ["galapro", "apicad", "lecturio", "archives-miriadi-anciennes", "christian", "jean-pierre"],
    evidence: [
      { interview: "Christian", note: "Rappelle l'idée de mutualisation et d'innovation pour un réseau de l'intercompréhension à distance." },
      { interview: "Encarni", note: "Situe Miriadi comme étape après Galanet et Galapro." },
      { interview: "Jean-Pierre Chavagne", note: "Décrit Miriadi comme projet et plateforme à la fois riche et difficile à récupérer informatiquement." },
    ],
    recovery: {
      priority: "moyenne",
      status: "à inventorier",
      nextAction: "Distinguer le site vivant, les anciennes sessions et les ressources réellement exportables.",
      responsible: "à définir",
      contacts: ["christian", "jean-pierre", "apicad"],
    },
  },
  "archives-miriadi-anciennes": {
    relatedItems: ["miriadi", "apicad", "lecturio"],
    evidence: [
      { interview: "Christian", note: "Évoque le passage de certaines sessions de Miriadi vers Moodle." },
      { interview: "Sandrine", note: "Présente Miriadi comme réservoir de nombreuses ressources ou activités." },
    ],
    recovery: {
      priority: "moyenne",
      status: "à inventorier",
      nextAction: "Cartographier les anciennes sessions et repérer les ressources exportables ou documentables.",
      responsible: "à définir",
      contacts: ["christian", "jean-pierre", "hugues"],
    },
  },
  apicad: {
    relatedItems: ["miriadi", "lecturio", "archives-miriadi-anciennes", "hugues", "jean-pierre"],
    evidence: [
      { interview: "Christian", note: "Présente APICAD comme association prolongeant Miriadi et l'intercompréhension à distance." },
      { interview: "Jean-Pierre Chavagne", note: "Associe APICAD aux enjeux actuels de maintien des sites et ressources." },
      { interview: "Hugues", note: "Évoque APICAD à propos des difficultés concrètes de maintenance web." },
    ],
  },
  lecturio: {
    relatedItems: ["miriadi", "apicad", "encarni", "jean-pierre"],
    evidence: [
      { interview: "Encarni", note: "Définit Lecturio comme projet ou ressource de plurilinguisme et littératie lié à Miriadi." },
      { interview: "Jean-Pierre Chavagne", note: "Mentionne Lecturio comme projet affiché dans Miriadi." },
    ],
  },
  alpaga: {
    relatedItems: ["iplera", "repli4c", "romanofonia-cinema", "corpus-videos", "katia", "christian"],
    evidence: [
      { interview: "Kátia", note: "Présente ALPAGA comme prolongement d'IPLERA autour des pratiques plurilingues." },
      { interview: "Christian", note: "Relie ALPAGA à la constitution de corpus et aux questions de consentement." },
      { interview: "Alice", note: "Évoque les réunions ALPAGA comme ressources vidéo potentielles." },
    ],
  },
  repli4c: {
    relatedItems: ["alpaga", "romanofonia-cinema", "corpus-videos", "perennisation", "katia", "christian"],
    evidence: [
      { interview: "Kátia", note: "Situe REPLI4C dans la continuité d'ALPAGA et dans les enjeux de formats durables." },
      { interview: "Christian", note: "Le décrit comme projet actuel centré sur les récits liés au changement climatique." },
    ],
  },
  "romanofonia-cinema": {
    relatedItems: ["christian", "alpaga", "repli4c", "moodle", "miriadi"],
    evidence: [
      { interview: "Christian", note: "Décrit Romanofonía y Cinema comme dispositif passé de Miriadi à Moodle." },
      { interview: "Elena", note: "L'utilise comme cadre d'interproduction écrite puis orale." },
      { interview: "Kátia", note: "Relie les sessions Romanofonía aux corpus mobilisés dans ALPAGA et REPLI4C." },
    ],
  },
  speechmatics: {
    relatedItems: ["sandra", "elan", "corpus-multimodal", "annotation-transcription"],
    evidence: [
      { interview: "Sandra", note: "Décrit l'usage de Speechmatics pour obtenir une première transcription avant reprise manuelle." },
    ],
  },
  elan: {
    relatedItems: ["sandra", "speechmatics", "corpus-multimodal", "annotation-transcription"],
    evidence: [
      { interview: "Sandra", note: "Présente ELAN comme outil central pour l'annotation fine des interactions." },
      { interview: "Sandrine", note: "Mentionne ELAN dans les discussions sur les outils et traces." },
    ],
  },
  "corpus-multimodal": {
    relatedItems: ["sandra", "elan", "speechmatics", "corpus-videos", "nosketch-kiparla"],
    evidence: [
      { interview: "Sandra", note: "Fait émerger le besoin de relier audio, transcriptions, annotations et métadonnées." },
      { interview: "Alice", note: "Évoque des vidéos et réunions qui pourraient devenir matériaux exploitables." },
    ],
  },
  "corpus-videos": {
    relatedItems: ["alpaga", "repli4c", "ressources-unita", "corpus-multimodal", "annotation-transcription"],
    evidence: [
      { interview: "Alice", note: "Signale des réunions IC et ALPAGA pouvant constituer des ressources vidéo potentielles." },
      { interview: "Kátia", note: "Insiste sur les enjeux de corpus, formats et pérennisation." },
      { interview: "Sandra", note: "Relie l'exploitation des corpus aux besoins de transcription et d'annotation." },
    ],
    recovery: {
      priority: "haute",
      status: "à cadrer",
      nextAction: "Établir une liste de corpus vidéo ALPAGA / REPLI4C avec consentement, format, qualité audio et état de transcription.",
      responsible: "à définir",
      contacts: ["katia", "christian", "alice", "sandra"],
    },
  },
  "ressources-unita": {
    relatedItems: ["alice", "corpus-videos", "aides-comprehension-orale"],
    evidence: [
      { interview: "Alice", note: "Évoque les réunions UNITA comme matériau IC oral ou vidéo potentiellement exploitable." },
    ],
    recovery: {
      priority: "moyenne",
      status: "à vérifier",
      nextAction: "Demander quels enregistrements UNITA existent, sous quelles conditions et avec quelle qualité sonore.",
      responsible: "à définir",
      contacts: ["alice", "katia"],
    },
  },
  "elementi-unito": {
    relatedItems: ["sandra", "moodle", "aides-comprehension-orale", "eurom"],
    evidence: [
      { interview: "Sandra", note: "Présente le cours ouvert Elementi di intercomprensione UniTO comme ressource avec textes, vidéos et quiz." },
    ],
    recovery: {
      priority: "moyenne",
      status: "à documenter",
      nextAction: "Documenter l'URL, les droits de reprise et la structure pédagogique du cours.",
      responsible: "à définir",
      contacts: ["sandra"],
    },
  },
  "itineraires-romans": {
    relatedItems: ["galatea", "encarni", "hugues"],
    evidence: [
      { interview: "Encarni", note: "Associe Itinéraires romans à l'Union Latine et aux ressources historiques pour enfants." },
      { interview: "Hugues", note: "L'évoque dans le contexte des ressources perdues ou dépendantes de technologies anciennes." },
    ],
    recovery: {
      priority: "haute",
      status: "à rechercher",
      nextAction: "Chercher les traces archivées, captures ou copies locales, puis vérifier les contraintes liées à Flash et aux droits.",
      responsible: "à définir",
      contacts: ["encarni", "hugues"],
    },
  },
  "portail-ple-katia": {
    relatedItems: ["katia", "politique-linguistique", "perennisation"],
    evidence: [
      { interview: "Kátia", note: "Mentionne un portail PLE utile mais encore à identifier précisément." },
    ],
    recovery: {
      priority: "moyenne",
      status: "à clarifier",
      nextAction: "Redemander à Kátia le nom exact, l'URL et le statut du portail PLE cité.",
      responsible: "à définir",
      contacts: ["katia"],
    },
  },
  "aides-comprehension-orale": {
    relatedItems: ["eurom", "corpus-videos", "ressources-unita", "annotation-transcription", "laura", "alice", "sandra"],
    evidence: [
      { interview: "Laura", note: "Signale un manque de ressources pour le niveau 2 oral par rapport aux manuels d'écrit." },
      { interview: "Alice", note: "Relie les dispositifs pédagogiques aux besoins d'interaction orale." },
      { interview: "Sandra", note: "Montre que l'oral demande transcription, annotation et outillage spécifique." },
    ],
    recovery: {
      priority: "haute",
      status: "à concevoir",
      nextAction: "Lister les ressources orales existantes, les aides disponibles et les lacunes didactiques prioritaires.",
      responsible: "à définir",
      contacts: ["alice", "sandra", "laura"],
    },
  },
  christian: {
    relatedItems: ["romanofonia-cinema", "alpaga", "repli4c", "moodle", "miriadi", "galanet"],
    evidence: [
      { interview: "Christian", note: "Relie les projets historiques, Romanofonía, ALPAGA, REPLI4C, Moodle et la question d'un équivalent bibliothécaire." },
      { interview: "Kátia", note: "L'associe aux corpus et à la continuité ALPAGA / REPLI4C." },
    ],
  },
  encarni: {
    relatedItems: ["galatea", "galanet", "galapro", "miriadi", "evaluation", "lecturio"],
    evidence: [
      { interview: "Encarni", note: "Fournit une généalogie dense des projets Gala et de leurs transformations." },
      { interview: "Jean-Pierre Chavagne", note: "Confirme son rôle dans les plateformes historiques et la mémoire des dispositifs." },
    ],
  },
  "jean-pierre": {
    relatedItems: ["galanet", "galapro", "miriadi", "apicad", "galatea"],
    evidence: [
      { interview: "Jean-Pierre Chavagne", note: "Donne des détails sur Galanet, Galapro, Miriadi et les enjeux de récupération technique." },
      { interview: "Hugues", note: "Le cite dans les réseaux de ressources et de maintenance." },
    ],
  },
  katia: {
    relatedItems: ["sdl", "politique-linguistique", "perennisation", "iplera", "alpaga", "repli4c"],
    evidence: [
      { interview: "Kátia", note: "Insiste sur la pérennisation, les politiques linguistiques, ALPAGA, REPLI4C et la bibliothèque de ressources." },
    ],
  },
  sandra: {
    relatedItems: ["elan", "speechmatics", "corpus-multimodal", "nosketch-kiparla", "elementi-unito"],
    evidence: [
      { interview: "Sandra", note: "Documente les chaînes de transcription, annotation, corpus et outillage de consultation." },
      { interview: "Alice", note: "Croise les enjeux pédagogiques de l'oral et des ressources exploitables." },
    ],
  },
  eurom: {
    relatedItems: ["aides-comprehension-orale", "hugues", "richard", "sandra", "laura"],
    evidence: [
      { interview: "Sandra", note: "Montre EuRom Web comme interface avec audio, surlignage et aides." },
      { interview: "Laura", note: "Cite EuRom comme référence forte tout en signalant le manque pour l'oral avancé." },
      { interview: "Richard", note: "Rattache son entrée dans l'intercompréhension à EuRom." },
    ],
  },
  laura: {
    relatedItems: ["eurom", "aides-comprehension-orale", "dictionnaire-strategique"],
    evidence: [
      { interview: "Laura", note: "Cite EuRom comme référence tout en faisant apparaître un manque de ressources pour l'oral avancé." },
    ],
  },
  "politique-linguistique": {
    relatedItems: ["sdl", "iplera", "alpaga", "katia", "perennisation"],
    evidence: [
      { interview: "Kátia", note: "Relie IPLERA et ALPAGA aux politiques linguistiques universitaires." },
      { interview: "Christian", note: "Souligne les limites institutionnelles mises en évidence par IPLERA." },
    ],
  },
  perennisation: {
    relatedItems: ["centralisation", "politique-linguistique", "katia", "miriadi", "apicad"],
    evidence: [
      { interview: "Kátia", note: "Insiste sur les formats durables et la transmission des ressources." },
      { interview: "Christian", note: "Formule le besoin d'une fonction proche des bibliothécaires pour conserver et rendre accessible." },
      { interview: "Hugues", note: "Rappelle les coûts et difficultés de maintenance web." },
    ],
  },
  centralisation: {
    relatedItems: ["perennisation", "dictionnaire-strategique", "annotation-transcription", "miriadi"],
    evidence: [
      { interview: "Christian", note: "Exprime le besoin de conserver, classer, maintenir, convertir et rendre accessible." },
      { interview: "Kátia", note: "Fait émerger le besoin d'une bibliothèque de ressources durable." },
    ],
  },
  "annotation-transcription": {
    relatedItems: ["elan", "speechmatics", "corpus-multimodal", "aides-comprehension-orale"],
    evidence: [
      { interview: "Sandra", note: "Décrit une chaîne combinant transcription automatique, reprise manuelle et annotation fine." },
      { interview: "Richard", note: "Fait apparaître la transcription comme besoin lié aux ressources orales." },
    ],
  },
  moodle: {
    relatedItems: ["romanofonia-cinema", "christian", "elementi-unito", "miriadi"],
    evidence: [
      { interview: "Christian", note: "Explique le passage de Romanofonía y Cinema vers Moodle et les questions d'export/import." },
      { interview: "Sandra", note: "Présente un cours ouvert hébergé sur Moodle avec ressources et activités." },
    ],
  }
};

items.forEach((item) => {
  Object.assign(item, itemAugmentations[item.id] || {});
});

const v03Augmentations = {
  galatea: {
    confidence: "moyenne",
    sourceStatus: "transcription à vérifier",
    lastChecked: "2026-07-03",
    longDescription: "Galatea constitue l'un des points de départ de la mémoire numérique de l'intercompréhension romane. La fiche doit permettre de distinguer le projet, les CD-ROM, les éventuelles copies locales et les traces documentaires encore accessibles.",
    uncertaintyNote: "Le statut des supports et des droits doit être vérifié avant toute republication.",
    todo: ["Identifier les exemplaires de CD-ROM existants.", "Vérifier les droits et la compatibilité technique."],
    relations: [
      { target: "galanet", type: "prolonge", note: "Galanet s'inscrit dans la continuité de la saga Gala." },
      { target: "itineraires-romans", type: "cite", note: "Les deux ressources relèvent du patrimoine historique à retrouver." },
    ],
  },
  galanet: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "Galanet est une plateforme historique de télécollaboration entre groupes. Elle structure des échanges en phases, avec forum, chat, documents et production collective. La v0.3 la place au centre de la généalogie Galatea, Galanet, Galapro et Miriadi.",
    todo: ["Demander les captures ou exports disponibles.", "Documenter les fonctions exactes de la plateforme."],
    relations: [
      { target: "galatea", type: "hérite de", note: "Galanet reprend l'héritage de la première saga Gala." },
      { target: "galapro", type: "prolonge", note: "Galapro déplace le modèle vers la formation de formateurs." },
      { target: "miriadi", type: "documente", note: "Miriadi généralise et mutualise certains principes de Galanet/Galapro." },
      { target: "jean-pierre", type: "récupère", note: "Jean-Pierre est une personne ressource pour les traces techniques." },
    ],
  },
  galapro: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "Galapro prolonge Galanet en orientant l'intercompréhension vers la formation de formateurs et la didactique. Cette fiche sert à suivre les traces pédagogiques, les modules et les critères d'évaluation à récupérer.",
    todo: ["Inventorier les modules récupérables.", "Stabiliser la relation entre Galapro et évaluation."],
    relations: [
      { target: "galanet", type: "hérite de", note: "Galapro reprend une partie de la logique de plateforme et de sessions." },
      { target: "miriadi", type: "prolonge", note: "Miriadi arrive ensuite comme environnement de mutualisation plus large." },
      { target: "evaluation", type: "documente", note: "La formation de formateurs suppose des traces d'évaluation à expliciter." },
    ],
  },
  miriadi: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "Miriadi est à la fois une plateforme, un projet et un réseau. Sa valeur documentaire vient de son rôle de mutualisation, mais aussi de la fragilité de ses anciennes sessions et de la nécessité de distinguer site vivant, archives et ressources exportables.",
    todo: ["Séparer site vivant, anciennes sessions et archives.", "Repérer les ressources exportables."],
    relations: [
      { target: "galapro", type: "hérite de", note: "Miriadi arrive après Galanet/Galapro dans la chronologie des plateformes." },
      { target: "apicad", type: "maintient", note: "APICAD prolonge certains enjeux de réseau et de maintenance." },
      { target: "lecturio", type: "documente", note: "Lecturio est cité comme ressource ou projet affiché dans l'environnement Miriadi." },
      { target: "archives-miriadi-anciennes", type: "fragilise", note: "Les anciennes sessions posent un problème d'accès et de migration." },
    ],
  },
  apicad: {
    confidence: "moyenne",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    todo: ["Préciser ce qu'APICAD maintient concrètement.", "Identifier les responsables de maintenance web."],
    relations: [
      { target: "miriadi", type: "maintient", note: "APICAD est liée au prolongement et au maintien de l'écosystème Miriadi." },
      { target: "lecturio", type: "documente", note: "Lecturio est rattaché aux ressources suivies dans cet environnement." },
    ],
  },
  lecturio: {
    confidence: "à vérifier",
    sourceStatus: "transcription à vérifier",
    lastChecked: "2026-07-03",
    uncertaintyNote: "Le nom, le statut et le périmètre exact doivent être consolidés.",
    todo: ["Vérifier le nom exact.", "Retrouver la fiche ou page projet."],
    relations: [
      { target: "miriadi", type: "cite", note: "Lecturio est mentionné dans l'environnement Miriadi." },
      { target: "apicad", type: "documente", note: "La récupération passe probablement par les personnes liées à APICAD." },
    ],
  },
  alpaga: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "ALPAGA relie les pratiques plurilingues, les corpus, le consentement et la transition vers REPLI4C. La fiche sert de pivot entre politiques linguistiques, corpus et ressources vidéo.",
    todo: ["Lister les corpus et guides issus d'ALPAGA.", "Relier les traces vidéo aux statuts de consentement."],
    relations: [
      { target: "iplera", type: "hérite de", note: "ALPAGA prolonge des questions ouvertes par IPLERA." },
      { target: "repli4c", type: "prolonge", note: "REPLI4C s'inscrit dans la continuité d'ALPAGA." },
      { target: "corpus-videos", type: "documente", note: "ALPAGA a produit ou signalé des traces exploitables comme corpus." },
    ],
  },
  repli4c: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "REPLI4C est le projet actuel dans lequel s'inscrit le stage. Il organise des enjeux de corpus, de discours climatiques, de pérennisation et de réutilisation des ressources.",
    todo: ["Préciser les corpus disponibles.", "Documenter les formats durables à privilégier."],
    relations: [
      { target: "alpaga", type: "hérite de", note: "REPLI4C reprend un socle de questions et de corpus d'ALPAGA." },
      { target: "romanofonia-cinema", type: "utilise", note: "Romanofonía y Cinema fait partie des corpus ou dispositifs mobilisables." },
      { target: "perennisation", type: "documente", note: "REPLI4C rend visibles les besoins de transmission et de maintenance." },
    ],
  },
  "romanofonia-cinema": {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "Romanofonía y Cinema est un dispositif de télécollaboration contemporain, héritier de certains modèles historiques et aujourd'hui lié à Moodle. Il est important pour l'interproduction et les corpus actuels.",
    todo: ["Documenter les exports Moodle possibles.", "Décrire les types de productions étudiantes."],
    relations: [
      { target: "miriadi", type: "hérite de", note: "Les sessions précédentes ont été liées à Miriadi." },
      { target: "moodle", type: "utilise", note: "Le dispositif fonctionne désormais sur Moodle." },
      { target: "repli4c", type: "documente", note: "Il alimente les corpus utiles à REPLI4C." },
    ],
  },
  sandra: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "Sandra est une personne ressource pour comprendre la chaîne corpus, transcription, annotation et consultation. Sa fiche relie Speechmatics, ELAN, NoSketch Engine, KiParla et les enjeux de corpus multimodal.",
    todo: ["Lister les formats d'annotation utilisés.", "Préciser les modèles de métadonnées."],
    relations: [
      { target: "elan", type: "utilise", note: "ELAN est central pour l'annotation fine." },
      { target: "speechmatics", type: "utilise", note: "Speechmatics sert à produire une première transcription." },
      { target: "corpus-multimodal", type: "documente", note: "Les outils décrits par Sandra structurent le corpus multimodal." },
    ],
  },
  elan: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    todo: ["Décrire les couches d'annotation utiles à l'IC.", "Relier ELAN à un format d'export durable."],
    relations: [
      { target: "sandra", type: "utilise", note: "Sandra décrit ELAN comme outil d'annotation." },
      { target: "corpus-multimodal", type: "documente", note: "ELAN structure la couche d'annotation du corpus." },
      { target: "speechmatics", type: "prolonge", note: "L'annotation fine prolonge la transcription automatique." },
    ],
  },
  speechmatics: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    todo: ["Vérifier les langues et coûts utiles.", "Documenter la qualité de segmentation."],
    relations: [
      { target: "sandra", type: "utilise", note: "Sandra décrit l'usage actuel de Speechmatics." },
      { target: "elan", type: "prolonge", note: "La transcription produite est reprise et alignée dans ELAN." },
      { target: "annotation-transcription", type: "documente", note: "L'outil rend visible la chaîne IA puis correction humaine." },
    ],
  },
  "corpus-multimodal": {
    confidence: "moyenne",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "Le corpus multimodal est une fiche conceptuelle qui agrège les enjeux d'oral, vidéo, transcription, annotation, métadonnées et consultation. Elle prépare une exploitation scientifique plus systématique.",
    todo: ["Définir un schéma de métadonnées minimal.", "Relier chaque corpus à ses droits et formats."],
    relations: [
      { target: "elan", type: "utilise", note: "ELAN sert à annoter les interactions." },
      { target: "speechmatics", type: "utilise", note: "Speechmatics peut amorcer la transcription." },
      { target: "corpus-videos", type: "récupère", note: "Les vidéos récupérées peuvent alimenter le corpus." },
    ],
  },
  "itineraires-romans": {
    confidence: "moyenne",
    sourceStatus: "transcription à vérifier",
    lastChecked: "2026-07-03",
    uncertaintyNote: "Le statut exact de la ressource et des copies accessibles doit être vérifié.",
    todo: ["Chercher une archive web.", "Identifier les droits Union Latine."],
    relations: [
      { target: "galatea", type: "cite", note: "Ressource historique à rapprocher des premiers supports IC." },
      { target: "perennisation", type: "fragilise", note: "La disparition ou l'obsolescence illustre le problème de pérennisation." },
    ],
  },
  "aides-comprehension-orale": {
    confidence: "moyenne",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "Les aides à la compréhension orale regroupent un besoin transversal : produire des supports, guidages et scénarios pour un domaine moins équipé que l'écrit, en lien avec les corpus audio et vidéo.",
    todo: ["Lister les types d'aides existants.", "Définir les besoins prioritaires pour le niveau 2 oral."],
    relations: [
      { target: "eurom", type: "hérite de", note: "Les aides à l'oral peuvent s'inspirer de dispositifs de guidage existants pour l'écrit." },
      { target: "corpus-multimodal", type: "utilise", note: "Les aides nécessitent des corpus transcrits et annotés." },
      { target: "annotation-transcription", type: "documente", note: "La didactisation de l'oral dépend de la transcription et de l'annotation." },
    ],
  },
  christian: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    todo: ["Demander les archives Galanet/Miriadi disponibles.", "Préciser les exports Moodle utiles."],
    relations: [
      { target: "romanofonia-cinema", type: "documente", note: "Christian décrit le dispositif et son passage à Moodle." },
      { target: "alpaga", type: "documente", note: "Christian relie ALPAGA aux corpus et au consentement." },
      { target: "repli4c", type: "documente", note: "Christian situe REPLI4C comme projet actuel." },
      { target: "moodle", type: "utilise", note: "Moodle est l'infrastructure actuelle de certains dispositifs." },
    ],
  },
  encarni: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    todo: ["Vérifier les traces historiques qu'elle peut indiquer.", "Consolider la chronologie Gala."],
    relations: [
      { target: "galanet", type: "documente", note: "Encarni situe Galanet dans la saga historique." },
      { target: "galapro", type: "documente", note: "Elle décrit Galapro comme déplacement vers la didactique." },
      { target: "miriadi", type: "documente", note: "Elle relie Miriadi aux étapes précédentes." },
      { target: "evaluation", type: "cite", note: "L'évaluation devient importante dans les dispositifs de formation." },
    ],
  },
  "jean-pierre": {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    todo: ["Demander captures ou traces Galanet/Galapro.", "Préciser les archives APICAD."],
    relations: [
      { target: "galanet", type: "documente", note: "Jean-Pierre décrit les fonctions centrales de Galanet." },
      { target: "galapro", type: "documente", note: "Il relie Galapro à la formation de formateurs." },
      { target: "miriadi", type: "documente", note: "Il participe à la mémoire de Miriadi." },
      { target: "apicad", type: "maintient", note: "APICAD porte une partie des enjeux de maintien." },
    ],
  },
  katia: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    todo: ["Clarifier le portail PLE cité.", "Préciser les ressources à pérenniser en priorité."],
    relations: [
      { target: "sdl", type: "documente", note: "Kátia relie le prototype au cadre des sciences du langage." },
      { target: "politique-linguistique", type: "documente", note: "Elle situe IPLERA et ALPAGA dans les politiques linguistiques." },
      { target: "perennisation", type: "documente", note: "Elle insiste sur formats, bibliothèque et transmission." },
    ],
  },
  "politique-linguistique": {
    confidence: "moyenne",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    todo: ["Relier IPLERA à ses documents institutionnels.", "Préciser la place des formations universitaires."],
    relations: [
      { target: "iplera", type: "documente", note: "IPLERA fait émerger les limites des politiques linguistiques universitaires." },
      { target: "alpaga", type: "prolonge", note: "ALPAGA prolonge certaines questions institutionnelles vers les pratiques." },
      { target: "perennisation", type: "fragilise", note: "L'absence de politique de maintenance fragilise les ressources." },
    ],
  },
  perennisation: {
    confidence: "haute",
    sourceStatus: "confirmé",
    lastChecked: "2026-07-03",
    longDescription: "La pérennisation est un besoin central du prototype : elle transforme la mémoire des projets en actions de conservation, documentation, maintenance et transmission.",
    todo: ["Définir un statut de source.", "Ajouter responsable et date de vérification par fiche."],
    relations: [
      { target: "centralisation", type: "prolonge", note: "Centraliser ne suffit pas sans stratégie de maintenance." },
      { target: "apicad", type: "maintient", note: "APICAD illustre une réponse associative au maintien." },
      { target: "itineraires-romans", type: "récupère", note: "Les ressources disparues rendent la pérennisation concrète." },
    ],
  },
};

items.forEach((item) => {
  Object.assign(item, {
    confidence: item.confidence || "moyenne",
    sourceStatus: item.sourceStatus || (item.uncertain ? "incertain" : "transcription à vérifier"),
    lastChecked: item.lastChecked || "2026-07-03",
    todo: item.todo || [],
    relations: item.relations || [],
  }, v03Augmentations[item.id] || {});
});

const v04CommunityAugmentations = {
  galatea: {
    communityUse: "Point d'entrée pour comprendre les premiers supports numériques d'intercompréhension romane.",
    reuseHint: "Peut inspirer une séquence courte de compréhension écrite ou une comparaison entre anciens supports et usages actuels.",
    contributionHint: "Ajouter captures, copies consultables, informations de droits et témoignages d'usage.",
    audience: ["enseignants", "chercheurs", "réseaux / associations"],
  },
  galanet: {
    communityUse: "Modèle historique pour concevoir des échanges de groupes, forums, chats et productions collectives.",
    reuseHint: "Réutiliser la logique de phases pour créer un scénario collaboratif contemporain.",
    contributionHint: "Signaler captures, exports, anciens participants, guides ou productions finales.",
    audience: ["enseignants", "chercheurs", "ingénieurs pédagogiques", "réseaux / associations"],
  },
  galapro: {
    communityUse: "Repère pour former des formateurs à l'intercompréhension et documenter les scénarios pédagogiques.",
    reuseHint: "Adapter ses principes pour concevoir des modules de formation d'enseignants.",
    contributionHint: "Ajouter modules, critères d'évaluation, traces de formation ou responsables.",
    audience: ["enseignants", "chercheurs", "ingénieurs pédagogiques"],
  },
  miriadi: {
    communityUse: "Réservoir et réseau pour retrouver des sessions, ressources et acteurs de l'intercompréhension à distance.",
    reuseHint: "Identifier des activités ou principes de mutualisation à transposer dans un environnement actuel.",
    contributionHint: "Distinguer ressources vivantes, archives anciennes, liens morts et personnes à contacter.",
    audience: ["enseignants", "chercheurs", "réseaux / associations", "ingénieurs pédagogiques"],
  },
  apicad: {
    communityUse: "Point d'appui collectif pour comprendre qui peut maintenir, documenter ou transmettre certaines ressources.",
    reuseHint: "S'en servir comme repère de gouvernance pour organiser une récupération collective.",
    contributionHint: "Ajouter contacts, responsabilités, sites maintenus et actions possibles.",
    audience: ["réseaux / associations", "chercheurs", "ingénieurs pédagogiques"],
  },
  alpaga: {
    communityUse: "Repère pour relier pratiques plurilingues, corpus, consentement et ressources réutilisables.",
    reuseHint: "S'appuyer sur ses guides ou corpus pour concevoir des activités autour des pratiques plurilingues.",
    contributionHint: "Ajouter guides, corpus, formats, responsables et conditions de réutilisation.",
    audience: ["chercheurs", "enseignants", "ingénieurs pédagogiques"],
  },
  repli4c: {
    communityUse: "Cadre actuel pour relier corpus, discours climatiques et intercompréhension.",
    reuseHint: "Utiliser les corpus et scénarios comme matériaux pour activités de compréhension, interaction ou analyse.",
    contributionHint: "Documenter les corpus, formats, droits, transcriptions et possibilités d'annotation.",
    audience: ["chercheurs", "enseignants", "ingénieurs pédagogiques"],
  },
  "romanofonia-cinema": {
    communityUse: "Dispositif réutilisable pour penser télécollaboration, interproduction et échanges plurilingues.",
    reuseHint: "Adapter la structure de session à d'autres thèmes, langues ou publics.",
    contributionHint: "Ajouter scénarios, consignes, exports Moodle, productions et conditions de réutilisation.",
    audience: ["enseignants", "ingénieurs pédagogiques", "chercheurs"],
  },
  eurom: {
    communityUse: "Référence pédagogique pour concevoir des activités de compréhension écrite plurilingue.",
    reuseHint: "Servir de modèle de guidage, d'aides et de progression pour d'autres langues ou supports.",
    contributionHint: "Ajouter versions, liens, activités dérivées et retours d'usage.",
    audience: ["enseignants", "chercheurs"],
  },
  sandra: {
    communityUse: "Personne ressource pour comprendre la chaîne transcription, annotation et corpus oral.",
    reuseHint: "S'appuyer sur les outils cités pour préparer un protocole de corpus multimodal.",
    contributionHint: "Ajouter formats, modèles de métadonnées, outils utilisés et exemples de flux de travail.",
    audience: ["chercheurs", "ingénieurs pédagogiques"],
  },
  elan: {
    communityUse: "Outil de référence pour annoter finement des interactions orales ou multimodales.",
    reuseHint: "Peut structurer une chaîne de transcription, segmentation et annotation réutilisable.",
    contributionHint: "Ajouter tutoriels, modèles de couches et formats d'export.",
    audience: ["chercheurs", "ingénieurs pédagogiques"],
  },
  speechmatics: {
    communityUse: "Outil possible pour amorcer la transcription automatique de ressources orales.",
    reuseHint: "Peut accélérer une première passe avant correction humaine et annotation.",
    contributionHint: "Ajouter langues testées, qualité observée, coûts et précautions de données.",
    audience: ["chercheurs", "ingénieurs pédagogiques"],
  },
  "corpus-multimodal": {
    communityUse: "Cadre commun pour transformer vidéos et interactions en ressources analysables et didactisables.",
    reuseHint: "Servir de modèle pour définir métadonnées, transcription, annotation et droits.",
    contributionHint: "Ajouter corpus disponibles, niveaux d'annotation, formats et responsables.",
    audience: ["chercheurs", "ingénieurs pédagogiques", "enseignants"],
  },
  "itineraires-romans": {
    communityUse: "Ressource patrimoniale à retrouver pour documenter les premiers usages IC auprès des enfants.",
    reuseHint: "Peut inspirer des activités ludiques ou historiques si les supports sont récupérés.",
    contributionHint: "Chercher archives web, copies locales, captures et informations de droits.",
    audience: ["enseignants", "chercheurs", "réseaux / associations"],
  },
  "aides-comprehension-orale": {
    communityUse: "Besoin partagé pour rendre l'oral plus accessible dans les parcours d'intercompréhension.",
    reuseHint: "Transformer transcriptions, extraits audio et annotations en aides graduées pour apprenants.",
    contributionHint: "Ajouter exemples d'aides, scénarios, corpus audio et difficultés observées.",
    audience: ["enseignants", "ingénieurs pédagogiques", "chercheurs"],
  },
  "corpus-videos": {
    communityUse: "Réservoir potentiel de matériaux oraux ou multimodaux à rendre exploitables.",
    reuseHint: "Peut alimenter des activités d'écoute, d'analyse d'interaction ou de formation.",
    contributionHint: "Ajouter consentement, qualité audio, formats, transcriptions et responsables.",
    audience: ["chercheurs", "enseignants", "ingénieurs pédagogiques"],
  },
  christian: {
    communityUse: "Personne ressource pour relier projets historiques, dispositifs actuels, Moodle et corpus.",
    reuseHint: "Orienter les demandes d'archives, d'historique ou de scénarios de télécollaboration.",
    contributionHint: "Ajouter projets associés, ressources connues et contacts complémentaires.",
    audience: ["chercheurs", "réseaux / associations", "enseignants"],
  },
  encarni: {
    communityUse: "Personne ressource pour documenter la généalogie Galatea, Galanet, Galapro, Miriadi.",
    reuseHint: "Aider à reconstituer les continuités pédagogiques et historiques entre plateformes.",
    contributionHint: "Ajouter traces, précisions chronologiques et ressources citées.",
    audience: ["chercheurs", "réseaux / associations"],
  },
  "jean-pierre": {
    communityUse: "Personne ressource pour les plateformes historiques, leurs fonctions et leurs archives techniques.",
    reuseHint: "Orienter une récupération ou documentation de Galanet, Galapro, Miriadi et APICAD.",
    contributionHint: "Ajouter captures, descriptions techniques, contacts et archives connues.",
    audience: ["chercheurs", "ingénieurs pédagogiques", "réseaux / associations"],
  },
  katia: {
    communityUse: "Personne ressource pour les liens entre politiques linguistiques, ALPAGA, REPLI4C et pérennisation.",
    reuseHint: "Orienter les questions de formats durables, bibliothèque et mutualisation.",
    contributionHint: "Ajouter portails cités, ressources à préserver et priorités de récupération.",
    audience: ["chercheurs", "réseaux / associations", "ingénieurs pédagogiques"],
  },
  perennisation: {
    communityUse: "Besoin transversal pour éviter que les ressources IC disparaissent avec les plateformes ou les personnes.",
    reuseHint: "Servir de grille d'audit pour évaluer formats, responsables, droits et maintenance.",
    contributionHint: "Ajouter pratiques de sauvegarde, responsables, dates de vérification et migrations réussies.",
    audience: ["réseaux / associations", "ingénieurs pédagogiques", "chercheurs"],
  },
};

items.forEach((item) => {
  Object.assign(item, {
    communityUse: item.communityUse || "Repère communautaire pour retrouver, documenter ou relier une ressource d'intercompréhension.",
    reuseHint: item.reuseHint || "Peut servir de point de départ pour concevoir, comparer ou adapter une activité ou une ressource.",
    contributionHint: item.contributionHint || "Ajouter liens, captures, responsables, versions récupérables ou retours d'usage.",
    audience: item.audience || ["enseignants", "chercheurs", "réseaux / associations"],
  }, v04CommunityAugmentations[item.id] || {});
});

const v05SharingAugmentations = {
  galanet: {
    licenseStatus: "à vérifier",
    accessStatus: "à retrouver",
    rightsNote: "Droits, exports et données utilisateurs à vérifier avant toute diffusion publique.",
    communityPriority: "haute",
    communityPriorityReason: "Plateforme historique souvent citée, utile aux enseignants, chercheurs et réseaux.",
  },
  galapro: {
    licenseStatus: "à vérifier",
    accessStatus: "à retrouver",
    rightsNote: "Modules et traces de formation à vérifier avant réutilisation.",
    communityPriority: "haute",
    communityPriorityReason: "Ressource structurante pour la formation de formateurs en IC.",
    audience: ["enseignants", "chercheurs", "ingénieurs pédagogiques", "formation de formateurs"],
  },
  galatea: {
    licenseStatus: "à vérifier",
    accessStatus: "à retrouver",
    rightsNote: "Droits des CD-ROM et conditions de numérisation à clarifier.",
    communityPriority: "haute",
    communityPriorityReason: "Patrimoine fondateur pour comprendre l'histoire des ressources IC.",
  },
  miriadi: {
    licenseStatus: "à vérifier",
    accessStatus: "accès limité",
    rightsNote: "Distinguer ressources publiques, sessions anciennes et données de participants.",
    communityPriority: "haute",
    communityPriorityReason: "Point de mutualisation majeur pour plusieurs générations de ressources.",
  },
  "itineraires-romans": {
    licenseStatus: "à vérifier",
    accessStatus: "inaccessible",
    rightsNote: "Ressource patrimoniale liée à l'Union Latine ; droits et archives à vérifier.",
    communityPriority: "haute",
    communityPriorityReason: "Ressource fragile utile pour documenter la mémoire des supports jeunesse.",
  },
  "romanofonia-cinema": {
    licenseStatus: "restreint",
    accessStatus: "accès limité",
    rightsNote: "Réutilisation dépendante des productions, consentements et exports Moodle.",
    communityPriority: "haute",
    communityPriorityReason: "Dispositif actuel réutilisable pour télécollaboration et interproduction.",
  },
  repli4c: {
    licenseStatus: "à vérifier",
    accessStatus: "accès limité",
    rightsNote: "Corpus et discours à vérifier selon consentement, formats et finalités de recherche.",
    communityPriority: "haute",
    communityPriorityReason: "Projet actuel reliant corpus, climat, ressources et pratiques plurilingues.",
  },
  "corpus-videos": {
    licenseStatus: "restreint",
    accessStatus: "accès limité",
    rightsNote: "Consentement, anonymisation, qualité audio et droits vidéo à vérifier.",
    communityPriority: "haute",
    communityPriorityReason: "Matériau à fort potentiel pour enseignants, chercheurs et ingénieurs pédagogiques.",
  },
  "ressources-unita": {
    licenseStatus: "à vérifier",
    accessStatus: "à retrouver",
    rightsNote: "Existence, consentement et conditions de partage des enregistrements à clarifier.",
    communityPriority: "moyenne",
    communityPriorityReason: "Piste intéressante pour l'oral et les interactions institutionnelles.",
  },
  "elementi-unito": {
    licenseStatus: "à vérifier",
    accessStatus: "accessible",
    rightsNote: "Cours ouvert à documenter précisément avant reprise ou adaptation.",
    communityPriority: "moyenne",
    communityPriorityReason: "Ressource pédagogique actuelle, utile aux enseignants.",
  },
  "portail-ple-katia": {
    licenseStatus: "inconnu",
    accessStatus: "à retrouver",
    rightsNote: "Nom exact, URL et conditions de réutilisation à clarifier.",
    communityPriority: "haute",
    communityPriorityReason: "Référence potentiellement utile à plusieurs publics mais encore incertaine.",
  },
  phip: {
    licenseStatus: "à vérifier",
    accessStatus: "accessible",
    rightsNote: "Vérifier conditions de reprise des contes, images, textes et traductions.",
    communityPriority: "haute",
    communityPriorityReason: "Portail plurilingue directement partageable avec enseignants et réseaux.",
  },
  eurom: {
    licenseStatus: "à vérifier",
    accessStatus: "accessible",
    rightsNote: "Distinguer consultation, citation, adaptation pédagogique et droits des supports.",
    communityPriority: "haute",
    communityPriorityReason: "Référence pédagogique majeure et immédiatement compréhensible par la communauté.",
  },
  elan: {
    licenseStatus: "réutilisable",
    accessStatus: "accessible",
    rightsNote: "Outil réutilisable ; vérifier surtout les droits des corpus annotés.",
    communityPriority: "moyenne",
    communityPriorityReason: "Outil important pour transformer l'oral en corpus partageable.",
  },
  speechmatics: {
    licenseStatus: "restreint",
    accessStatus: "accessible",
    rightsNote: "Service tiers : vérifier coût, conditions d'usage et données envoyées.",
    communityPriority: "moyenne",
    communityPriorityReason: "Utile pour amorcer des transcriptions, mais dépend d'un service externe.",
  },
};

items.forEach((item) => {
  Object.assign(item, {
    licenseStatus: item.licenseStatus || "inconnu",
    accessStatus: item.accessStatus || (["disparu", "à récupérer"].includes(item.status) ? "à retrouver" : "à vérifier"),
    rightsNote: item.rightsNote || "Droits à vérifier avant diffusion publique.",
    communityPriority: item.communityPriority || "moyenne",
    communityPriorityReason: item.communityPriorityReason || "Fiche utile pour retrouver, documenter ou relier des ressources IC.",
  }, v05SharingAugmentations[item.id] || {});
});

const actorDefaults = {
  communityUse: "Point d'entrée pour retrouver qui connaît, cite ou peut documenter une ressource d'intercompréhension.",
  reuseHint: "Utiliser cette fiche pour orienter une demande de précision, d'archive, de contact ou de validation.",
  contributionHint: "Compléter la fiche avec affiliations, ressources citées, liens et domaines d'expertise.",
  audience: ["enseignants", "chercheurs", "réseaux / associations"],
};

const interviewedActorIds = ["teurra", "laura", "richard", "thomas", "alice", "giovanna", "sandra", "elena", "roxana", "sandrine", "encarni", "jean-pierre", "christian", "katia", "hugues"];
const citedExistingActorIds = ["hugues", "jean-pierre", "encarni", "christian", "katia", "sandra"];
const citedOnlyActorIds = [
  "louise-dabene",
  "claire-blanche-benveniste",
  "paula-leone",
  "mariana-frontini",
  "laurent-baque",
  "eric-martin-marteau",
  "raquel-serrano-lopez",
  "magdalena-de-carlo",
  "lia-escarpe",
  "robin-bright",
  "timothee-liotard",
  "philippe-blanchet",
  "pierre-escude",
  "francisco-calvo-del-olmo",
  "salman-khan",
  "hugo-professor-hugo",
  "chassagne-castagne-reims",
];

const actorRegistryAugmentations = {
  christian: {
    aliases: ["Christian", "Degache", "Degâge", "De Gache", "Christian Degache"],
    domains: ["Galanet", "Miriadi", "ALPAGA", "REPLI4C", "Romanofonía", "Moodle"],
    affiliations: ["UGA"],
    mentionedProjects: ["Galanet", "Galapro", "Miriadi", "ALPAGA", "REPLI4C", "Romanofonía y Cinema"],
    mentionedResources: ["Moodle", "corpus vidéo"],
    citedBy: ["Kátia", "Jean-Pierre Chavagne", "Encarni"],
  },
  encarni: {
    aliases: ["Encarni", "Encarnación Carrasco", "Encarnación Carrasco Perea", "Encarni Carrasco"],
    domains: ["Galatea", "Galanet", "Galapro", "Miriadi", "évaluation"],
    mentionedProjects: ["Galatea", "Galanet", "Galapro", "Miriadi", "Lecturio"],
    citedBy: ["Jean-Pierre Chavagne", "Christian Degache"],
  },
  "jean-pierre": {
    aliases: ["JP", "Jean-Pierre", "Chavagne", "Jean Pierre Chavagne", "Jean-Pierre Chavagne"],
    domains: ["Galanet", "Galapro", "Miriadi", "APICAD", "maintenance"],
    mentionedProjects: ["Galanet", "Galapro", "Miriadi", "APICAD", "EuRom"],
    citedBy: ["Encarni Carrasco", "Hugues Sheeren", "Christian Degache"],
  },
  katia: {
    aliases: ["Katia", "Kátia"],
    domains: ["IPLERA", "ALPAGA", "REPLI4C", "politique linguistique", "pérennisation"],
    mentionedProjects: ["IPLERA", "ALPAGA", "REPLI4C", "Portail PLE"],
    citedBy: ["Christian Degache", "Teurra"],
  },
  hugues: {
    aliases: ["Hugues", "Hugues Scheren", "Hugues Sheeren"],
    domains: ["EuRom", "Miriadi", "APICAD", "maintenance web"],
    mentionedProjects: ["EuRom", "Miriadi", "APICAD"],
    citedBy: ["Jean-Pierre Chavagne", "Richard"],
  },
  sandra: {
    aliases: ["Sandra", "Sandra Garbarino", "Garbarino"],
    domains: ["oral", "corpus", "ELAN", "Speechmatics", "EuRom Web", "intercompréhension", "enseignement", "recherche"],
    mentionedProjects: ["EuRom Web", "ELAN", "Speechmatics", "NoSketch Engine", "KiParla"],
    mentionedResources: ["corpus multimodal", "Elementi di intercomprensione UniTO"],
    citedBy: ["Alice", "Encarni", "Jean-Pierre Chavagne", "à compléter"],
    communityUse: "Personne interviewée et citée pour comprendre la chaîne transcription, annotation, corpus oral, EuRom Web et l'outillage de recherche.",
    reuseHint: "S'appuyer sur les outils et ressources cités pour préparer un protocole de corpus multimodal ou une démonstration autour de l'oral.",
    contributionHint: "Ajouter affiliations, publications, ressources citées, liens vers cours ou corpus et précisions sur les contextes de citation.",
    audience: ["chercheurs", "ingénieurs pédagogiques", "enseignants", "réseaux / associations"],
  },
  alice: {
    aliases: ["Alice"],
    domains: ["COIL", "oral", "Galanet", "ALPAGA", "EuRom"],
    mentionedProjects: ["Galanet", "ALPAGA", "UNITA", "EuRom"],
    mentionedResources: ["corpus vidéo", "aides à la compréhension orale"],
    citedBy: ["Sandra", "Thomas"],
  },
  laura: {
    aliases: ["Laura"],
    domains: ["EuRom", "oral", "dictionnaire stratégique", "compréhension"],
    mentionedProjects: ["EuRom", "aides à la compréhension orale"],
    mentionedResources: ["dictionnaire stratégique"],
    citedBy: ["Hugues", "Richard"],
  },
  richard: {
    aliases: ["Richard"],
    domains: ["PHIP", "EuRom", "dictionnaire", "transcription"],
    mentionedProjects: ["PHIP", "EuRom"],
    mentionedResources: ["Historias Infantiles Plurilingües", "dictionnaire stratégique"],
    citedBy: ["Hugues", "Jean-Pierre Chavagne"],
  },
  thomas: {
    aliases: ["Thomas"],
    domains: ["oral", "interproduction", "dictionnaire", "enseignement"],
    mentionedProjects: ["interproduction", "dictionnaire stratégique"],
    citedBy: ["Alice"],
  },
  teurra: {
    aliases: ["Teurra"],
    domains: ["à vérifier"],
    mentionedProjects: ["Kátia", "politique linguistique"],
  },
  giovanna: {
    aliases: ["Giovanna"],
    domains: ["EuRom", "intercompréhension"],
    mentionedProjects: ["EuRom"],
  },
  elena: {
    aliases: ["Elena"],
    domains: ["Romanofonía", "télécollaboration"],
    mentionedProjects: ["Romanofonía y Cinema"],
  },
  roxana: {
    aliases: ["Roxana"],
    domains: ["dictionnaire stratégique", "didactique"],
    mentionedProjects: ["dictionnaire stratégique"],
  },
  sandrine: {
    aliases: ["Sandrine"],
    domains: ["centralisation", "annotation", "Miriadi"],
    mentionedProjects: ["Miriadi", "centralisation", "annotation-transcription"],
  },
  "louise-dabene": {
    aliases: ["Louise Dabène", "Louise Dabene", "Dabène", "Dabene"],
    domains: ["didactique", "intercompréhension", "histoire"],
    citedBy: ["à compléter"],
  },
  "claire-blanche-benveniste": {
    aliases: ["Claire Blanche-Benveniste", "Claire Blanche Benveniste", "Blanche-Benveniste", "Blanche Benveniste"],
    domains: ["EuRom", "linguistique", "langues romanes"],
    mentionedProjects: ["EuRom", "EuRom 5"],
    citedBy: ["à compléter"],
  },
  "paula-leone": {
    aliases: ["Paula Leone", "Leone"],
    domains: ["intercompréhension", "enseignement"],
    citedBy: ["à compléter"],
  },
  "mariana-frontini": {
    aliases: ["Mariana Frontini", "Frontini"],
    domains: ["corpus", "ressources", "intercompréhension"],
    citedBy: ["à compléter"],
  },
  "laurent-baque": {
    aliases: ["Laurent Baqué", "Laurent Baque", "Baqué", "Baque"],
    domains: ["oral", "phonétique", "intercompréhension"],
    citedBy: ["à compléter"],
  },
  "eric-martin-marteau": {
    aliases: ["Eric Martin", "Éric Martin", "Eric Marteau", "Éric Marteau"],
    domains: ["nom à vérifier"],
    citedBy: ["à compléter"],
  },
  "raquel-serrano-lopez": {
    aliases: ["Raquel Serrano López", "Raquel Serrano Lopez", "Serrano López", "Serrano Lopez"],
    domains: ["intercompréhension", "enseignement"],
    citedBy: ["à compléter"],
  },
  "magdalena-de-carlo": {
    aliases: ["Magdalena de Carlo", "Magdalena De Carlo", "De Carlo"],
    domains: ["intercompréhension", "didactique", "formation"],
    citedBy: ["à compléter"],
  },
  "lia-escarpe": {
    aliases: ["Lia Escarpe", "Escarpe"],
    domains: ["intercompréhension", "ressources"],
    citedBy: ["à compléter"],
  },
  "robin-bright": {
    aliases: ["Robin Bright", "Bright"],
    domains: ["intercompréhension", "outillage", "ressources"],
    citedBy: ["à compléter"],
  },
  "timothee-liotard": {
    aliases: ["Timothée Liotard", "Timothee Liotard", "Liotard"],
    domains: ["intercompréhension", "outillage", "ressources"],
    citedBy: ["à compléter"],
  },
  "philippe-blanchet": {
    aliases: ["Philippe Blanchet", "Blanchet"],
    domains: ["sociolinguistique", "didactique", "politique linguistique"],
    citedBy: ["à compléter"],
  },
  "pierre-escude": {
    aliases: ["Pierre Escudé", "Pierre Escude", "Escudé", "Escude"],
    domains: ["intercompréhension", "didactique", "langues romanes"],
    citedBy: ["à compléter"],
  },
  "francisco-calvo-del-olmo": {
    aliases: ["Francisco Calvo del Olmo", "Paco", "Calvo del Olmo", "Francisco Calvo"],
    domains: ["intercompréhension", "langues romanes"],
    citedBy: ["à compléter"],
  },
  "salman-khan": {
    aliases: ["Salman Khan", "Khan Academy"],
    domains: ["référence externe", "pédagogie", "ressources"],
    citedBy: ["à compléter"],
  },
  "hugo-professor-hugo": {
    aliases: ["Hugo", "Professor Hugo", "Professeur Hugo"],
    domains: ["nom à vérifier", "ressource", "pédagogie"],
    citedBy: ["à compléter"],
  },
  "chassagne-castagne-reims": {
    aliases: ["Chassagne", "Castagne", "Chassagne Reims", "Castagne Reims"],
    domains: ["nom à vérifier", "Reims"],
    citedBy: ["à compléter"],
  },
  apicad: {
    actorKind: "institution / collectif",
    interviewed: false,
    domains: ["association", "réseau", "maintenance", "Miriadi"],
    mentionedProjects: ["Miriadi", "Lecturio", "Galanet", "Galapro"],
    citedBy: ["Jean-Pierre Chavagne", "Christian Degache", "Hugues Sheeren"],
  },
};

items.forEach((item) => {
  if (!["acteur", "acteur collectif", "institution"].includes(item.type)) return;
  const interviewed = interviewedActorIds.includes(item.id);
  const cited = citedExistingActorIds.includes(item.id) || citedOnlyActorIds.includes(item.id);
  const defaultActorKind = item.type === "acteur collectif" || item.type === "institution"
    ? "institution / collectif"
    : interviewed && cited
      ? "personne interviewée et citée"
      : interviewed
        ? "personne interviewée"
        : "personne citée";
  Object.assign(item, actorDefaults, {
    actorKind: item.actorKind || defaultActorKind,
    interviewed: item.interviewed ?? interviewed,
    domains: item.domains || [],
    affiliations: item.affiliations || [],
    mentionedProjects: item.mentionedProjects || [],
    mentionedResources: item.mentionedResources || [],
    citedBy: item.citedBy || [],
    aliases: item.aliases || [],
  }, actorRegistryAugmentations[item.id] || {});
});

const graphRows = [
  {
    actor: { id: "christian", label: "Christian" },
    project: { id: "romanofonia-cinema", label: "Romanofonía" },
    resource: { id: "repli4c", label: "REPLI4C" },
    note: "Christian documente un dispositif actuel qui nourrit les corpus et les questions de REPLI4C.",
  },
  {
    actor: { id: "sandra", label: "Sandra Garbarino" },
    project: { id: "elan", label: "ELAN" },
    resource: { id: "corpus-multimodal", label: "corpus multimodal" },
    note: "Sandra relie transcription, annotation et consultation de corpus.",
  },
  {
    actor: { id: "encarni", label: "Encarni" },
    project: { id: "galanet", label: "Galanet" },
    resource: { id: "miriadi", label: "Miriadi" },
    note: "Encarni rend lisible la généalogie Galatea, Galanet, Galapro, Miriadi.",
  },
  {
    actor: { id: "jean-pierre", label: "Jean-Pierre" },
    project: { id: "apicad", label: "APICAD" },
    resource: { id: "galapro", label: "Galapro" },
    note: "Jean-Pierre relie mémoire technique, formation de formateurs et maintien associatif.",
  },
  {
    actor: { id: "katia", label: "Kátia" },
    project: { id: "politique-linguistique", label: "politique linguistique" },
    resource: { id: "perennisation", label: "pérennisation" },
    note: "Kátia fait apparaître la chaîne institutionnelle qui mène au besoin de pérenniser.",
  },
];

const needs = [
  {
    title: "Centraliser",
    description: "Offrir un point d'entrée commun pour retrouver projets, ressources, personnes et traces.",
    tags: ["bibliothèque", "moteur de recherche"],
  },
  {
    title: "Mutualiser",
    description: "Rendre les supports partageables et réutilisables entre enseignants, chercheurs et projets.",
    tags: ["réseau", "réemploi"],
  },
  {
    title: "Pérenniser",
    description: "Prévoir formats, documentation, responsables et migrations au lieu de dépendre de plateformes fragiles.",
    tags: ["formats", "maintenance"],
  },
  {
    title: "Adapter / remixer",
    description: "Permettre de reprendre des ressources existantes pour d'autres langues, publics ou scénarios.",
    tags: ["didactisation", "variantes"],
  },
  {
    title: "Maintenir",
    description: "Identifier ce qui nécessite un webmaster, une association, un financement ou une relève.",
    tags: ["gouvernance", "APICAD"],
  },
  {
    title: "Retrouver",
    description: "Documenter les ressources perdues, les noms incertains, les URL et les personnes à contacter.",
    tags: ["archives", "vérification"],
  },
  {
    title: "Annoter",
    description: "Rendre les interactions exploitables par couches, métadonnées et segments alignés.",
    tags: ["ELAN", "corpus"],
  },
  {
    title: "Transcrire",
    description: "Combiner transcription automatique, correction humaine et formats durables.",
    tags: ["Speechmatics", "oral"],
  },
  {
    title: "Didactiser l'oral",
    description: "Créer des aides, parcours et supports pour un domaine jugé moins équipé que l'écrit.",
    tags: ["oral", "guidage"],
  },
  {
    title: "Créer une bibliothèque",
    description: "Classer manuels, plateformes, corpus, outils, guides et vidéos avec états et relations.",
    tags: ["catalogue", "documentation"],
  },
  {
    title: "Créer un dictionnaire stratégique",
    description: "Décrire les stratégies, passerelles et gestes d'intercompréhension utiles aux apprenants.",
    tags: ["stratégies", "lexique"],
  },
  {
    title: "Accompagner les enseignants",
    description: "Fournir des scénarios, ressources prêtes à adapter et repères pour entrer dans l'IC.",
    tags: ["formation", "ressources"],
  },
];

const filters = [
  { label: "Tous", mode: "all", value: "all" },
  { label: "Projets", mode: "type", value: "projet" },
  { label: "Acteurs", mode: "type", value: "acteur" },
  { label: "Ressources", mode: "type", value: "ressource" },
  { label: "Outils", mode: "type", value: "outil" },
  { label: "Corpus", mode: "type", value: "corpus" },
  { label: "Concepts", mode: "type", value: "concept" },
  { label: "Besoins", mode: "type", value: "besoin" },
  { label: "À récupérer", mode: "status", value: "à récupérer" },
  { label: "Fragile", mode: "status", value: "fragile" },
  { label: "Disparu", mode: "status", value: "disparu" },
  { label: "Vivant", mode: "status", value: "vivant" },
  { label: "Pour enseignants", mode: "audience", value: "enseignants" },
  { label: "Pour chercheurs", mode: "audience", value: "chercheurs" },
  { label: "Pour ingénieurs pédagogiques", mode: "audience", value: "ingénieurs pédagogiques" },
  { label: "Pour réseaux / associations", mode: "audience", value: "réseaux / associations" },
  { label: "Pour formation de formateurs", mode: "audience", value: "formation de formateurs" },
];
